name: dorossii-webhook

services:
  webhook:
    build:
      context: .
    hostname: webhook
    restart: always
    ports:
      - 0.0.0.0:9000:9000
    env_file:
      - path: ${HOST_INFRA_DIR}/config/webhook.env
        required: true
    volumes:
      - ${HOST_WEBHOOK_DIR}/hooks.json:/etc/webhook/hooks.json:ro
      - ${HOST_WEBHOOK_DIR}/deploy.sh:${HOST_WEBHOOK_DIR}/deploy.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_INFRA_DIR}:${HOST_INFRA_DIR}
    command:
      - -hooks=/etc/webhook/hooks.json
      - -port=9000
      - -verbose
      - -hotreload
      - -template
